// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:841c91fe-8e1d-447d-950d-2bb0fbc5310a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5uY2t7yt4",
    "aws_user_pools_web_client_id": "6msf91r0r48f408a9tc6d7oih7"
};


export default awsmobile;
