// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3632d7e6-6337-4698-9db3-294671964654",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_19RjDchF2",
    "aws_user_pools_web_client_id": "6ol7pio9fsu0taf9ocf4t9c0mc"
};


export default awsmobile;
